"""Strict, provider-independent models for explicit entity linking.

The models in this module keep A3.1 ``GraphEntity`` objects as document-scoped
local facts.  Canonical entities, link decisions, and memberships are separate
records so a linking run can be replaced or reversed without rewriting the
extracted graph.
"""

from __future__ import annotations

import hashlib
import json
import math
import unicodedata
from collections.abc import Mapping
from datetime import UTC, datetime
from typing import Final, Literal, Self
from uuid import UUID, uuid4

from pydantic import BaseModel, ConfigDict, Field, PrivateAttr, field_validator, model_validator

CANONICAL_ENTITY_SCHEMA_VERSION: Final = "1.0"
LINKING_SCHEMA_VERSION: Final = "1.0"
LINKING_ID_VERSION: Final = "v2"
CANONICAL_ENTITY_ID_VERSION: Final = "v1"
DEFAULT_DECISION_RUN_ID: Final = UUID(int=0)

LinkDecision = Literal["LINK", "NO_LINK", "UNCERTAIN"]
LinkMethod = Literal[
    "incompatible_type",
    "no_shared_signal",
    "deterministic_rule",
    "similarity_rule",
    "manual_review",
    "llm_adjudication",
    "llm_invalid_output",
    "llm_unavailable",
]


class LinkingPayloadError(ValueError):
    """Raised when an LLM adjudication is not the exact JSON contract."""


class _LinkingBaseModel(BaseModel):
    """Shared strict validation for application-owned linking records."""

    model_config = ConfigDict(extra="forbid")


def _clean_text(value: str, field_name: str) -> str:
    cleaned = " ".join(unicodedata.normalize("NFKC", value).strip().split())
    if not cleaned:
        raise ValueError(f"{field_name} must contain at least one non-whitespace character")
    return cleaned


def normalize_linking_label(value: str) -> str:
    """Normalize a label for matching while preserving display values separately."""

    return " ".join(unicodedata.normalize("NFKC", value).strip().casefold().split())


def _normalized_text(value: str, field_name: str) -> str:
    return normalize_linking_label(_clean_text(value, field_name))


def _strict_json_confidence(value: object) -> float:
    """Accept JSON numbers only; reject bool/string coercion at the provider boundary."""

    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise ValueError("confidence must be a JSON number")
    try:
        confidence = float(value)
    except (OverflowError, ValueError) as error:
        raise ValueError("confidence must be a finite JSON number") from error
    if not math.isfinite(confidence):
        raise ValueError("confidence must be a finite JSON number")
    if not 0 <= confidence <= 1:
        raise ValueError("confidence must be between 0 and 1")
    return confidence


def linking_identity_json(kind: str, payload: Mapping[str, object]) -> str:
    """Serialize a versioned identity with deterministic, unambiguous JSON."""

    envelope = {
        "identity_schema_version": LINKING_ID_VERSION,
        "kind": kind,
        "payload": dict(payload),
    }
    return json.dumps(
        envelope,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
        allow_nan=False,
    )


def _digest_id(kind: str, payload: Mapping[str, object]) -> str:
    digest = hashlib.sha256(linking_identity_json(kind, payload).encode("utf-8")).hexdigest()
    return f"{kind}_{LINKING_ID_VERSION}_{digest}"


def _validate_digest_id(value: str, *, kind: str) -> str:
    cleaned = _clean_text(value, f"{kind}_id")
    prefix = f"{kind}_{LINKING_ID_VERSION}_"
    if not (cleaned.startswith(prefix) and len(cleaned) == len(prefix) + 64):
        raise ValueError(f"{kind}_id must be generated by the linking identity helper")
    try:
        int(cleaned.removeprefix(prefix), 16)
    except ValueError as error:
        raise ValueError(f"{kind}_id must contain a hexadecimal digest") from error
    return cleaned


def _validate_opaque_id(value: str, *, kind: str, version: str = "v1") -> str:
    cleaned = _clean_text(value, f"{kind}_id")
    prefix = f"{kind}_{version}_"
    if not (cleaned.startswith(prefix) and len(cleaned) == len(prefix) + 32):
        raise ValueError(f"{kind}_id must be an opaque generated UUID")
    try:
        int(cleaned.removeprefix(prefix), 16)
    except ValueError as error:
        raise ValueError(f"{kind}_id must contain a hexadecimal UUID") from error
    return cleaned


def _validate_local_entity_id(value: str) -> str:
    cleaned = _clean_text(value, "local_entity_id")
    prefix = "entity_v2_"
    if not (cleaned.startswith(prefix) and len(cleaned) == len(prefix) + 64):
        raise ValueError("local_entity_id must be an A3.1 entity_id")
    try:
        int(cleaned.removeprefix(prefix), 16)
    except ValueError as error:
        raise ValueError("local_entity_id must contain a hexadecimal digest") from error
    return cleaned


def new_canonical_entity_id() -> str:
    """Create an opaque lifecycle identity for a newly persisted canonical entity."""

    return f"canonical_entity_{CANONICAL_ENTITY_ID_VERSION}_{uuid4().hex}"


def link_pair_id_for(
    knowledge_base_id: UUID,
    local_entity_a_id: str,
    local_entity_b_id: str,
) -> str:
    """Build a stable unordered identity for a local-entity pair."""

    first = _validate_local_entity_id(local_entity_a_id)
    second = _validate_local_entity_id(local_entity_b_id)
    if first == second:
        raise ValueError("a link candidate must contain two distinct local entities")
    first, second = sorted((first, second))
    return _digest_id(
        "link_pair",
        {
            "knowledge_base_id": str(knowledge_base_id),
            "local_entity_a_id": first,
            "local_entity_b_id": second,
        },
    )


def link_decision_id_for(
    knowledge_base_id: UUID,
    local_entity_a_id: str,
    local_entity_b_id: str,
    run_id: UUID | None = None,
) -> str:
    """Build a deterministic decision identity for one pair within one run."""

    pair_id = link_pair_id_for(knowledge_base_id, local_entity_a_id, local_entity_b_id)
    return _digest_id(
        "link_decision",
        {"link_pair_id": pair_id, "run_id": str(run_id or DEFAULT_DECISION_RUN_ID)},
    )


def canonical_link_id_for(
    knowledge_base_id: UUID,
    local_entity_id: str,
    canonical_entity_id: str,
) -> str:
    """Build a stable identity for one local-to-canonical membership."""

    local = _validate_local_entity_id(local_entity_id)
    canonical = _validate_opaque_id(canonical_entity_id, kind="canonical_entity")
    return _digest_id(
        "canonical_link",
        {
            "knowledge_base_id": str(knowledge_base_id),
            "local_entity_id": local,
            "canonical_entity_id": canonical,
        },
    )


def _deduplicate_labels(values: list[str], *, exclude: str | None = None) -> list[str]:
    excluded = normalize_linking_label(exclude) if exclude is not None else None
    choices: dict[str, str] = {}
    for value in values:
        cleaned = _clean_text(value, "alias")
        normalized = normalize_linking_label(cleaned)
        if normalized and normalized != excluded:
            choices.setdefault(normalized, cleaned)
    return [choices[key] for key in sorted(choices)]


def _validate_id_list(values: list[str]) -> list[str]:
    normalized = [_validate_digest_id(value, kind="link_decision") for value in values]
    if len(normalized) != len(set(normalized)):
        raise ValueError("supporting_decision_ids must be unique")
    return sorted(normalized)


class CandidateSignals(_LinkingBaseModel):
    """Auditable, application-computed signals for one candidate pair."""

    normalized_name_match: bool
    mention_overlap: list[str] = Field(default_factory=list)
    alias_overlap: list[str] = Field(default_factory=list)
    compatible_entity_type: bool
    lexical_similarity: float = Field(ge=0, le=1)
    same_document: bool

    @field_validator("mention_overlap", "alias_overlap")
    @classmethod
    def normalize_overlaps(cls, values: list[str]) -> list[str]:
        return _deduplicate_labels(values)


class CanonicalEntity(_LinkingBaseModel):
    """A knowledge-base-scoped entity with an opaque persistent lifecycle ID."""

    schema_version: Literal["1.0"] = CANONICAL_ENTITY_SCHEMA_VERSION
    canonical_entity_id: str
    knowledge_base_id: UUID
    canonical_name: str = Field(min_length=1, max_length=500)
    entity_type: str = Field(min_length=1, max_length=100)
    aliases: list[str] = Field(default_factory=list, max_length=100)
    _initial_canonical_entity_id: str | None = PrivateAttr(default=None)
    _initial_knowledge_base_id: UUID | None = PrivateAttr(default=None)
    _initial_entity_type: str | None = PrivateAttr(default=None)

    @field_validator("canonical_entity_id")
    @classmethod
    def validate_canonical_entity_id(cls, value: str) -> str:
        return _validate_opaque_id(value, kind="canonical_entity")

    @field_validator("canonical_name")
    @classmethod
    def validate_canonical_name(cls, value: str) -> str:
        return _clean_text(value, "canonical_name")

    @field_validator("entity_type")
    @classmethod
    def validate_entity_type(cls, value: str) -> str:
        return _clean_text(value, "entity_type")

    @field_validator("aliases")
    @classmethod
    def normalize_aliases(cls, values: list[str]) -> list[str]:
        return _deduplicate_labels(values)

    @model_validator(mode="after")
    def exclude_canonical_name_from_aliases(self) -> Self:
        self.aliases = _deduplicate_labels(self.aliases, exclude=self.canonical_name)
        if self._initial_canonical_entity_id is None:
            self._initial_canonical_entity_id = self.canonical_entity_id
            self._initial_knowledge_base_id = self.knowledge_base_id
            self._initial_entity_type = self.entity_type
        return self


class EntityLinkCandidate(_LinkingBaseModel):
    """One deterministic, unordered local-entity candidate pair."""

    schema_version: Literal["1.0"] = LINKING_SCHEMA_VERSION
    link_pair_id: str
    knowledge_base_id: UUID
    local_entity_a_id: str
    local_entity_b_id: str
    signals: CandidateSignals

    @field_validator("link_pair_id")
    @classmethod
    def validate_link_pair_id(cls, value: str) -> str:
        return _validate_digest_id(value, kind="link_pair")

    @field_validator("local_entity_a_id", "local_entity_b_id")
    @classmethod
    def validate_local_ids(cls, value: str) -> str:
        return _validate_local_entity_id(value)

    @model_validator(mode="after")
    def validate_identity(self) -> Self:
        if self.local_entity_a_id >= self.local_entity_b_id:
            raise ValueError("candidate local entity IDs must be in deterministic order")
        expected = link_pair_id_for(
            self.knowledge_base_id,
            self.local_entity_a_id,
            self.local_entity_b_id,
        )
        if self.link_pair_id != expected:
            raise ValueError("link_pair_id does not match the candidate identity")
        return self


class EntityLinkDecision(_LinkingBaseModel):
    """One historical LINK/NO_LINK/UNCERTAIN decision for a candidate pair."""

    schema_version: Literal["1.0"] = LINKING_SCHEMA_VERSION
    decision_id: str
    link_pair_id: str
    run_id: UUID
    knowledge_base_id: UUID
    local_entity_a_id: str
    local_entity_b_id: str
    decision: LinkDecision
    method: LinkMethod
    confidence: float | None = Field(default=None, ge=0, le=1)
    reason: str = Field(min_length=1, max_length=500)
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    candidate_signals: CandidateSignals
    provider: str | None = Field(default=None, min_length=1, max_length=100)
    model: str | None = Field(default=None, min_length=1, max_length=200)
    prompt_version: str | None = Field(default=None, min_length=1, max_length=100)

    @field_validator("decision_id")
    @classmethod
    def validate_decision_id(cls, value: str) -> str:
        return _validate_digest_id(value, kind="link_decision")

    @field_validator("link_pair_id")
    @classmethod
    def validate_link_pair_id(cls, value: str) -> str:
        return _validate_digest_id(value, kind="link_pair")

    @field_validator("local_entity_a_id", "local_entity_b_id")
    @classmethod
    def validate_local_ids(cls, value: str) -> str:
        return _validate_local_entity_id(value)

    @field_validator("reason")
    @classmethod
    def normalize_reason(cls, value: str) -> str:
        return _clean_text(value, "reason")

    @field_validator("created_at")
    @classmethod
    def normalize_created_at(cls, value: datetime) -> datetime:
        if value.tzinfo is None:
            return value.replace(tzinfo=UTC)
        return value.astimezone(UTC)

    @model_validator(mode="after")
    def validate_identity(self) -> Self:
        if self.local_entity_a_id >= self.local_entity_b_id:
            raise ValueError("decision local entity IDs must be in deterministic order")
        if self.decision == "LINK" and not self.candidate_signals.compatible_entity_type:
            raise ValueError("LINK decision requires compatible entity types")
        expected_pair = link_pair_id_for(
            self.knowledge_base_id,
            self.local_entity_a_id,
            self.local_entity_b_id,
        )
        if self.link_pair_id != expected_pair:
            raise ValueError("link_pair_id does not match the decision pair")
        expected_decision = link_decision_id_for(
            self.knowledge_base_id,
            self.local_entity_a_id,
            self.local_entity_b_id,
            self.run_id,
        )
        if self.decision_id != expected_decision:
            raise ValueError("decision_id does not match the decision identity")
        return self


class EntityCanonicalLink(_LinkingBaseModel):
    """A reversible membership supported by one or more LINK decisions."""

    schema_version: Literal["1.0"] = LINKING_SCHEMA_VERSION
    link_id: str
    knowledge_base_id: UUID
    local_entity_id: str
    canonical_entity_id: str
    decision_id: str
    supporting_decision_ids: list[str] = Field(default_factory=list, max_length=100)
    method: LinkMethod
    confidence: float | None = Field(default=None, ge=0, le=1)
    reason: str = Field(min_length=1, max_length=500)
    candidate_signals: CandidateSignals
    provider: str | None = Field(default=None, min_length=1, max_length=100)
    model: str | None = Field(default=None, min_length=1, max_length=200)
    prompt_version: str | None = Field(default=None, min_length=1, max_length=100)

    @field_validator("link_id")
    @classmethod
    def validate_link_id(cls, value: str) -> str:
        return _validate_digest_id(value, kind="canonical_link")

    @field_validator("decision_id")
    @classmethod
    def validate_decision_id(cls, value: str) -> str:
        return _validate_digest_id(value, kind="link_decision")

    @field_validator("supporting_decision_ids")
    @classmethod
    def validate_supporting_decision_ids(cls, values: list[str]) -> list[str]:
        return _validate_id_list(values)

    @field_validator("local_entity_id")
    @classmethod
    def validate_local_entity_id(cls, value: str) -> str:
        return _validate_local_entity_id(value)

    @field_validator("canonical_entity_id")
    @classmethod
    def validate_canonical_entity_id(cls, value: str) -> str:
        return _validate_opaque_id(value, kind="canonical_entity")

    @field_validator("reason")
    @classmethod
    def normalize_reason(cls, value: str) -> str:
        return _clean_text(value, "reason")

    @model_validator(mode="after")
    def validate_identity(self) -> Self:
        if not self.supporting_decision_ids:
            self.supporting_decision_ids = [self.decision_id]
        if self.decision_id not in self.supporting_decision_ids:
            raise ValueError("decision_id must be one of supporting_decision_ids")
        if self.decision_id != min(self.supporting_decision_ids):
            raise ValueError("decision_id must be the deterministic primary support decision")
        expected = canonical_link_id_for(
            self.knowledge_base_id,
            self.local_entity_id,
            self.canonical_entity_id,
        )
        if self.link_id != expected:
            raise ValueError("link_id does not match the membership identity")
        return self


class LinkAdjudicationOutput(_LinkingBaseModel):
    """The only provider output accepted for an ambiguous candidate."""

    decision: LinkDecision
    confidence: float | None = Field(default=None, ge=0, le=1)
    reason: str = Field(min_length=1, max_length=500)

    @field_validator("confidence", mode="before")
    @classmethod
    def validate_confidence(cls, value: object) -> float:
        return _strict_json_confidence(value)

    @field_validator("reason")
    @classmethod
    def normalize_reason(cls, value: str) -> str:
        return _clean_text(value, "reason")


def _reject_duplicate_json_keys(pairs: list[tuple[str, object]]) -> dict[str, object]:
    payload: dict[str, object] = {}
    for key, value in pairs:
        if key in payload:
            raise LinkingPayloadError(f"linking response contains duplicate key: {key}")
        payload[key] = value
    return payload


def _reject_json_constant(value: str) -> None:
    raise LinkingPayloadError(f"linking response contains unsupported JSON constant: {value}")


def parse_link_adjudication_output(text: str) -> LinkAdjudicationOutput:
    """Parse one strict JSON object and reject IDs, duplicate keys, or prose."""

    stripped = text.strip()
    if stripped.startswith("```") and stripped.endswith("```"):
        lines = stripped.splitlines()
        if len(lines) < 3 or lines[0].strip().lower() not in {"```", "```json"}:
            raise LinkingPayloadError("linking response has an invalid JSON code fence")
        stripped = "\n".join(lines[1:-1]).strip()
    try:
        payload = json.loads(
            stripped,
            object_pairs_hook=_reject_duplicate_json_keys,
            parse_constant=_reject_json_constant,
        )
    except LinkingPayloadError:
        raise
    except (TypeError, json.JSONDecodeError) as error:
        raise LinkingPayloadError("linking response was not valid JSON") from error
    if not isinstance(payload, dict):
        raise LinkingPayloadError("linking response must be a JSON object")
    try:
        return LinkAdjudicationOutput.model_validate(payload)
    except Exception as error:
        raise LinkingPayloadError("linking response failed the strict schema") from error


__all__ = [
    "CANONICAL_ENTITY_ID_VERSION",
    "CANONICAL_ENTITY_SCHEMA_VERSION",
    "DEFAULT_DECISION_RUN_ID",
    "LINKING_ID_VERSION",
    "LINKING_SCHEMA_VERSION",
    "CandidateSignals",
    "CanonicalEntity",
    "EntityCanonicalLink",
    "EntityLinkCandidate",
    "EntityLinkDecision",
    "LinkAdjudicationOutput",
    "LinkDecision",
    "LinkMethod",
    "LinkingPayloadError",
    "canonical_link_id_for",
    "link_decision_id_for",
    "link_pair_id_for",
    "linking_identity_json",
    "new_canonical_entity_id",
    "normalize_linking_label",
    "parse_link_adjudication_output",
]
