"""Provider-independent graph models and the Neo4j infrastructure adapter."""

from .models import (
    GRAPH_ID_VERSION,
    GRAPH_SCHEMA_VERSION,
    EntityId,
    ExtractionProvenance,
    GraphEntity,
    GraphProvenance,
    GraphRelation,
    RelationId,
    canonical_identity_json,
    entity_id_for,
    evidence_id_for,
    relation_id_for,
)
from .neo4j import (
    NEO4J_LINK_PAIR_LABEL,
    GraphDeleteResult,
    GraphLinkDeleteResult,
    GraphLinkUpsertResult,
    GraphStoreError,
    GraphUpsertResult,
    Neo4jGraphStore,
    Neo4jReadiness,
)
from .retrieval import (
    GRAPH_RETRIEVAL_SCHEMA_VERSION,
    GraphCanonicalReference,
    GraphEntityReference,
    GraphEntitySnapshot,
    GraphEvidence,
    GraphEvidenceResult,
    GraphNeighbor,
    GraphPath,
    GraphRelationReference,
    GraphRetrievalConfig,
    GraphRetrievalResult,
    GraphSeedCandidate,
)
from .retrieval_service import GraphRetrievalError, GraphRetrievalService, GraphRetrievalStore

__all__ = [
    "GRAPH_ID_VERSION",
    "GRAPH_RETRIEVAL_SCHEMA_VERSION",
    "GRAPH_SCHEMA_VERSION",
    "NEO4J_LINK_PAIR_LABEL",
    "EntityId",
    "ExtractionProvenance",
    "GraphCanonicalReference",
    "GraphDeleteResult",
    "GraphEntity",
    "GraphEntityReference",
    "GraphEntitySnapshot",
    "GraphEvidence",
    "GraphEvidenceResult",
    "GraphLinkDeleteResult",
    "GraphLinkUpsertResult",
    "GraphNeighbor",
    "GraphPath",
    "GraphProvenance",
    "GraphRelation",
    "GraphRelationReference",
    "GraphRetrievalConfig",
    "GraphRetrievalError",
    "GraphRetrievalResult",
    "GraphRetrievalService",
    "GraphRetrievalStore",
    "GraphSeedCandidate",
    "GraphStoreError",
    "GraphUpsertResult",
    "Neo4jGraphStore",
    "Neo4jReadiness",
    "RelationId",
    "canonical_identity_json",
    "entity_id_for",
    "evidence_id_for",
    "relation_id_for",
]
